#!/usr/bin/env bash

#description: execute tests on macOS

cd $(dirname "$0") || error "Failed to change directory to script location"

while [ ! -f Makefile ]; do
	cd .. || error "Failed to change directory to parent"
done

cat sercon.batch | make run
