#!/usr/bin/env bash

function cleanup() {
	rm -rf Doxyfile* latex
}

cd "$(dirname "$0")"

rm -rf Doxyfile* html latex

trap 'cleanup' EXIT

doxygen -g

sed -E -i '' 's/^INPUT.+/INPUT = src/g' Doxyfile
sed -E -i '' 's/^GENERATE_HTML.+/GENERATE_HTML = YES/g' Doxyfile
sed -E -i '' 's/^SEARCHENGINE.+/SEARCHENGINE = YES/g' Doxyfile

doxygen Doxyfile

open html/index.html
