#!/usr/bin/env bash

function cleanup {
		echo
		echo "Cleaning up..."
		docker system prune -f
}

set -euo pipefail

cd $(dirname "$0")/../docker

# Check if docker is installed
docker info >/dev/null 2>&1 || exit 1

trap cleanup EXIT

for d in * ; do
	[ -d "$d" ] || continue
	(
		cd "$d"
		linux=$(basename "$d")
		printf "================================================\n"
		printf "Building and running docker image for $(echo $linux | tr '[:lower:]' '[:upper:]')\n"
		printf "================================================\n"
		docker build --progress=plain -t "dev-sercon-${linux}" . || exit 1
		docker run --rm -it -v ~/sercon:/sercon "dev-sercon-${linux}" \
			bash -c "echo help | make run -- -H" || exit 1
	)
done
