#!/usr/bin/env bash

shopt -s nullglob

function cleanup() {
	if [ -n "$progress_pid" ]; then
		kill "$progress_pid" >/dev/null 2>&1
		wait "$progress_pid" >/dev/null 2>&1
	fi
	tput cnorm # show cursor
}

function error() {
	echo "Error: $@" >&2
	exit 1
}

function logpath() {
	echo "$logroot/$(basename "$1").log"
}

function test2title() {
	local title="$(basename "$1")"
	echo "${title/#$tests_prefix/}"
}

function progress() {
	local chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
	while true; do
		for ((i = 0; i < ${#chars}; i++)); do
			printf "%s\b" "${chars:i:1}"
			sleep 0.1
		done
	done
}

cd $(dirname "$0") || error "Failed to change directory to script location"

description_regex='^#[[:space:]]*[dD]escription:'
tests_root_dir="${PWD}/cases"
tests_prefix="test_"
logroot=/tmp
declare -A test_results || error "Bash 4+ required to run this script"

# get specific tests from command-line
while [ -n "$1" ]; do
	case "$1" in
		-h|--help)
			echo "Usage: $0 {-h|--help} {-l|--logdir <logdir>} [test1 test2 ...]"
			exit 0
			;;
		-l|--logdir)
			shift
			if [ -n "$1" ]; then
				logroot="$1"
				mkdir -p "$logroot" || error "Failed to create log directory: $logroot"
			fi
			;;
		*)
			# tests are specified by their name (without the prefix, e.g., "example" for "test_example")
			path="${tests_root_dir}/${tests_prefix}$1"
			[ -n "$path" ] && test_results["$path"]="not run"
			;;
	esac
	shift
done

# if no specific tests were provided, assume all tests in the cases directory
if [[ "${#test_results[@]}" -eq 0 ]]; then
	for test in ${tests_root_dir}/${tests_prefix}*; do
		test_results["$test"]="not run"
	done
fi

[ ${#test_results[@]} -eq 0 ] && error "No tests to run."

# run tests

trap 'cleanup' EXIT
tput civis # hide cursor
progress &
progress_pid=$!
index=0
for test in "${!test_results[@]}"; do
	# show progress message
	index=$((index + 1))
	printf "\r\033[2KRunning test %d/%d: %s " \
		"$index" "${#test_results[@]}" "$(test2title "$test")"
	# skip if the test file does not exist
	if [ ! -f "$test" ]; then
		test_results["$test"]="not found"
		continue
	fi
	# run the test and capture its output
	if bash -c "$test" >"$(logpath "$test")" 2>&1; then
		test_results["$test"]="passed"
	else
		test_results["$test"]="failed"
	fi
done
# kill progress indicator
kill "$progress_pid" >/dev/null 2>&1
wait "$progress_pid" >/dev/null 2>&1
progress_pid=""
tput cnorm # show cursor
printf "\r\033[2K" # clear the progress line

# summary

total=0
failures=0
for test in "${!test_results[@]}"; do
	description=$(cat "$test" 2>/dev/null | grep -E "$description_regex" | sed -E "s/$description_regex //")
	total=$((total + 1))
	title=$(basename "$test")
	result="${test_results[$test]}"
	case "$result" in
		passed)
			icon="✅ PASS"
			;;
		failed)
			icon="❌ FAIL"
			failures=$((failures + 1))
			;;
		"not found")
			icon="❓ NOT FOUND"
			failures=$((failures + 1))
			;;
		"not run")
			icon="⚠️ NOT RUN"
			failures=$((failures + 1))
			;;
	esac
	printf "%d) %-10s %s\n\tDescription: %s\n\tLog File: %s\n" \
		"$((total))" "$(test2title "$test")" "$icon" "${description}" "$(logpath "$test")"
done

echo
echo "Total tests: $total"
echo "Failures: $failures"

exit $failures
