#!/usr/bin/env bash

set -euo pipefail

cd $(dirname "$0")/../docker

for d in * ; do
	[ -d "$d" ] || continue
	(
		cd "$d"
		linux=$(basename "$d")
		printf "\x1b[33m================================================\x1b[0m\n"
		printf "\x1b[33mBuilding and running docker image for $(echo $linux | tr '[:lower:]' '[:upper:]')\x1b[0m\n"
		printf "\x1b[33m================================================\x1b[0m\n"
		docker build --progress=plain -t "dev-sercon-${linux}" . || exit 1
		docker run --rm -it -v ~/sercon:/sercon "dev-sercon-${linux}" \
			bash -c "echo help | make run -- -H" || exit 1
	)
done
