#!/usr/bin/env bash

logprefix="/tmp/build-"

function cleanup() {
	docker system prune -f >/dev/null 2>&1
}

function error() {
	echo "Error: $@" >&2
	exit 101
}

function build() {
	local dockerfile="$1"
	local extension="${dockerfile##*.}"
	local distro="${extension,,}"
	local image_name="dev-sercon-${distro,,}"
	(
		docker build --progress=plain -t "${image_name}" -f "${dockerfile}" . 2>&1
	) > "${logprefix}${distro}.log"
	ret=$?
	return ${ret}
}

function progress() {
	local chars="|/-\\"
	while true; do
		for ((i = 0; i < ${#chars}; i++)); do
			printf "%s\b" "${chars:i:1}"
			sleep 0.1
		done
	done
}

cd "$(dirname "$0")" || error "Failed to change directory to $(dirname "$0")"

rm -f "${logprefix}"*.log

docker info > /dev/null 2>&1 || error "Docker is not running or not accessible"
trap cleanup EXIT

failures=0
for dockerfile in Dockerfile.*; do
	distro="${dockerfile##*.}"
	distro="${distro,,}"
	printf "%s: " "${distro^}"
	progress &
	progress_pid=$!
	build "${dockerfile}"
	ret=$?
	kill "${progress_pid}" >/dev/null 2>&1
	wait "${progress_pid}" >/dev/null 2>&1
	[ "${ret}" -eq 0 ] && icon="✅" || icon="❌"
	printf "\r%s: ${icon} (%s)\n" "${distro^}" "${logprefix}${distro}.log"
	[ "${ret}" -ne 0 ] && failures=$((failures + 1))
done

exit ${failures}
