#!/usr/bin/env bash

function error() {
	echo "Error: $@" >&2
	exit 1
}

linux=$1
[ -n "$linux" ] || error "Usage: $0 <linux-distro>"

cd $(dirname "$0")

docker run --rm -it --privileged -v ~/sercon:/sercon --name sercon-${linux,,} dev-sercon-${linux,,} bash
